{{- define "ut.microservice" -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ut.fullname" . }}-{{ .params.name }}
  labels:
    app: {{ template "ut.name" . }}
    chart: {{ template "ut.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{ if hasKey .params "replicaCount" -}}
  replicas: {{ .params.replicaCount }}
  {{ else -}}
  replicas: {{ .Values.replicaCount }}
  {{ end -}}
  selector:
    matchLabels:
      app: {{ template "ut.name" . }}-{{ .params.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ut.name" . }}-{{ .params.name }}
        version: {{ .Chart.Version }}
        release: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-rc
      containers:
        - name: {{ .Chart.Name }}-eso-{{ .params.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: UT_ENV
            value: {{ .Values.microservice.env }}
          - name: UT_APP
            value: server/ms/{{ .params.app }}
          {{ if .params.http -}}
          ports:
            - containerPort: {{ .params.http }}
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: {{ .params.http }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .params.http }}
          {{ end -}}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/ut_standard_{{ .Values.microservice.env }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .params.name }}
  labels:
    app: {{ template "ut.name" . }}
    chart: {{ template "ut.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ default "ClusterIP" .params.type}}
  ports:
    - port: {{ default 8080 .params.http }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "ut.name" . }}-{{ .params.name }}
    release: {{ .Release.Name }}
{{- end -}}
