apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ut.fullname" . }}-core-db
  labels:
    app: {{ template "ut.name" . }}-core-db
    chart: {{ template "ut.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ut.name" . }}-core-db
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ut.name" . }}-core-db
        version: {{ .Chart.Version }}
        release: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-rc
      containers:
        - name: {{ .Chart.Name }}-esa-core
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['./impl-standard', 'server/ms/esaCore']
          volumeMounts:
          - name: config-volume
            mountPath: /etc/ut_standard_dev
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: db-core
  labels:
    app: {{ template "ut.name" . }}
    chart: {{ template "ut.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ template "ut.name" . }}-core-db
    release: {{ .Release.Name }}
