apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ template "ut.fullname" . }}-fluentd
  labels:
    app: {{ template "ut.name" . }}
    chart: {{ template "ut.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ut.name" . }}-fluentd
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ut.name" . }}-fluentd
        version: {{ .Chart.Version }}
        release: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: fluent/fluent-bit:0.14.3
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "/fluent-bit/bin/fluent-bit"
          - "-i"
          - "forward"
          - "-o"
          - "es"
          - "-p"
          - "Host={{ template "elasticsearch.fullname" . }}"
          - "-p"
          - "Port=9200"
          - "-p"
          - "Index=ut"
          - "-p"
          - "Type=log"
          - "-p"
          - "Buffer_Size=64KB"
          - "-p"
          - "Retry_Limit=1"
          - "-m"
          - "*"
          - "-o"
          - "stdout"
          - "-m"
          - "*"
          - "-v"
        name: fluentd
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  labels:
    app: {{ template "ut.name" . }}
    chart: {{ template "ut.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 24224
      protocol: TCP
      name: forward
  selector:
    app: {{ template "ut.name" . }}-fluentd
    release: {{ .Release.Name }}
