{{ $params := dict "params" (dict "name" "document" "app" "esoDocument") -}}
{{ $params := merge $params . -}}
{{ include "ut.microservice" $params -}}
---
{{ $params := dict "params" (dict "name" "db-document" "app" "esaDocument") -}}
{{ $params := merge $params . -}}
{{ include "ut.microservice" $params -}}