apiVersion: v1
appVersion: "7.2"
description: "impl-standard microservices"
name: ut
version: 1.0.0
icon: https://avatars3.githubusercontent.com/u/2078910?s=200&v=4
sources:
- https://softwaregroup.com